### ISSUE TITLE
Right click in menus goes back

### ISSUE THREAD

**Issue by SnowyTheDragon** [Kooluve/Better-Mouse-And-Gamepad#2]
Hello, I wanted to suggest the ability to right click in menus to quickly go back, as I like how other games do it.

**Comment by Kooluve** [comment]
Thank you for you suggestion!
Do you say you want to exit menu like click "esc" or back to previous menu if it has?
If it's the former, you can click middle button because I made it as "esc" when just click. Also you can open the .lua file, find "user settings" in the beginning, and exchange mapping of right and middle click. However, if you do so, the hold function will also exchange, you need to get used to this change. Separating click and hold function is unnecessary I think.
If it's the latter, the need is pretty same as "b" button of gamepad. Maybe I can change it for your file, but I think the previous way is already easy to use.
Right click in this mod is cancel all select, same as original game. I think it's a useful and high-frequency function. If change it, there seems no more other way to easily do this given that mouse button's number is limited. What do you think?

**Comment by Kooluve** [comment]
I'm sorry I tried a few hours to call go back function but it doesn't work for some unknown reason, so I given up in the end.
Fortunately the ui layers in this game isn't too many, so it's not too much trouble to click the back button. Hope you have fun with this game and mod!
